application: predictive-fx-831 
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
  secure: always

- url: /bootstrap/*
  static_dir: bootstrap
  secure: always
  
- url: /js
  static_dir: js
  secure: always

- url: /.*
  script: winebook.application
  secure: always
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest